// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorServer.Models
{
    public partial class Employee
    {
        public Employee()
        {
            TimeKeepingTransactions = new HashSet<TimeKeepingTransaction>();
        }

        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public DateTime? DateHired { get; set; }

        public virtual ICollection<TimeKeepingTransaction> TimeKeepingTransactions { get; set; }
    }
}