// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorServer.Models
{
    public partial class TimeKeepingTransaction
    {
        public int TimeKeepingTransactionTypeId { get; set; }
        public int? EmployeeId { get; set; }
        public int? TransactionTypeId { get; set; }
        public DateTime? TransactionDateTime { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}